[package]
name = "glint"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
image = { version = "0.25.2", features = ["rayon"] }
rand = "0.8.5"
rayon = "1.10.0"
